# Site Info
title:              "Grey Hat"
description:        "The Art of Hacking"

# Google APIs
google_verify:      # Your Google Verification - set to 'false' to disable
google_analytics:   UA-XXXXXXX-X # Your Google Analytics code - set to 'false' to disable

# Author Info
author_name:        "greyhat"
author_email:       #
author_gravatar:    8c6c103cdd6749798ae544155e6b34e7 # Gravatar md5 hash (of email) here for logo - set to 'false' to disable
twitter_username:   false # set to 'false' to disable
github_username:    greyhat # set to 'false' to disable

# Site Settings
url:                https://greyhat.github.io # main url
baseurl:            / # for gh-pages
permalink:          /notes/:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
